---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: demoapps-system
spec:
  generateSelector: true
  resyncPeriodSeconds: 30
  parentResource:
    apiVersion: example.com/v1
    resource: demoapps
  childResources:
    - apiVersion: apps/v1
      resource: deployments
    - apiVersion: v1
      resource: services
    - apiVersion: v1
      resource: serviceaccounts
  hooks:
    sync:
      webhook:
        url: http://demoapp-controller.demoapps-system.svc.cluster.local.:5000/sync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-controller
  labels:
    app: demoapp-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp-controller
  template:
    metadata:
      labels:
        app: demoapp-controller
    spec:
      containers:
        - name: demoapp-controller
          image: ttl.sh/demoapp-controller-2024-03-12:latest
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-controller
spec:
  selector:
    app: demoapp-controller
  ports:
    - port: 5000
      targetPort: http
