---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: demoapps.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    kind: DemoApp
    plural: demoapps
    singular: demoapp
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true # cheating here
    subresources:
      status: {}
